# Generated by Django 5.2.4 on 2025-07-30 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('title', models.CharField(max_length=250)),
                ('summary', models.TextField(blank=True)),
                ('content', models.TextField()),
                ('pub_date', models.DateField()),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
    ]
