# Generated by Django 5.2.4 on 2025-07-10 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('year', models.PositiveIntegerField()),
                ('pub_type', models.CharField(choices=[('J', 'Journal'), ('C', 'Conference'), ('P', 'Policy Brief')], max_length=1)),
                ('authors', models.CharField(max_length=255)),
                ('doi', models.CharField(blank=True, max_length=128)),
                ('pdf', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['-year', 'title'],
            },
        ),
    ]
