# Generated by Django 5.2.4 on 2025-07-16 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='pub_type',
        ),
        migrations.AddField(
            model_name='publication',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='publication',
            name='authors',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='publication',
            name='doi',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='publication',
            name='year',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
